### ISSUE TITLE
File Path not found

### ISSUE THREAD

**Issue by pavankumarmokkapati** [zoop/zoop-offline-aadhaar-android-sdk#17]
How to pass the path to download the aadhaar file. The code is commented in the sample app.

**Comment by divyank96** [comment]
you don't need to pass any path to download aadhaar file it will get downloaded automatically in user internal storgae of phone as a zip file and you will also get the json response from that zip file at your end.

**Comment by pavankumarmokkapati** [comment]
HI, while end of the authentication getting ZOOP_017 Error. 

"KYC ZIP download failed"

This is the error.
D/QT_SDK_LOGS::
{"error":{"code":"INVALID_URL","message":"Please check https://docs.zoop.one | You are trying to connect a wrong endpoint"}}
--

**Comment by pavankumarmokkapati** [comment]
Please provide the solution.

**Comment by divyank96** [comment]
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="<<YOUR PACKAGE NAME>>"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
```

Insert this in your manifest file with authority value of your package name
