### ISSUE TITLE
how to change Proceed  (Recommended ) text color

### ISSUE THREAD

**Issue by tejasCodenicely** [zoop/zoop-offline-aadhaar-android-sdk#22]
how to change Proceed (Recommended ) text color ?

**Comment by divyank96** [comment]
> how to change Proceed (Recommended ) text color ?

hey you can override 
    <color name="zoopWhite"><<your color>></color>
like this in your colors.xml file but it will change the color of other things too in sdk 
if you want to change the background color of button then you can put this in your color.xml file
 <color name="colorPrimaryDark"><<your color>></color>
