### ISSUE TITLE
null image name

### ISSUE THREAD

**Issue by kishorekethineni** [zoop/zoop-offline-aadhaar-android-sdk#23]
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/QT_FACEMATCH_IMG/null: open failed: ENOENT (No such file or directory)

using in `android 11`

At line 244 in `ZoopFaceMatchFragment.java`

please look into it @thefoodiecoder

**Comment by divyank96** [comment]
> ZoopFaceMatchFragment.java

hi can you please try using front camera rather than back camera once and let me know and also have you trried using our sample app once?

**Comment by kishorekethineni** [comment]
@divyank96 Yes tried same issue

**Comment by divyank96** [comment]
> @divyank96 Yes tried same issue

okay we are updating our sdk will send the new version on your mail
