### ISSUE TITLE
AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by vishgyana** [zoop/zoop-offline-aadhaar-android-sdk#26]
Execution failed for task ':app:processTvsdevDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/vgts/.gradle/caches/transforms-2/files-2.1/cd94c8dea7d6c31a51c7e8c8ea83e63d/jetified-offline_aadhaar-1.1.2/AndroidManifest.xml:30:5-50:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by divyank96** [comment]
can you try 1.1.3 version once?

**Comment by vishgyana** [comment]
> can you try 1.1.3 version once?

tried this working
