### ISSUE TITLE
Manifest Merging Issue is coming while adding aadhar release v1 .aar file

### ISSUE THREAD

**Issue by GauravAndroidIS** [zoop/zoop-offline-aadhaar-android-sdk#3]

**Comment by divyank96** [comment]
Hey, Gaurav
New offline_aadhaar_releaseV1.0.aar has been updated here can you please try to integrate this new aar and for Manifest Merging issue now it's solved you need to put file provider path here as mentioned in documentation but if still it occurs you can take a help from Sample App manifest file or attached your manifest code snippet here.

**Comment by divyank96** [comment]
I hope this issue has been resolved I am closing this issue.

**Comment by GauravAndroidIS** [comment]
Please wait let me test it first

**Comment by divyank96** [comment]
Sure let me know I have updated the new aar file you can test if problem still exist I will reopen the issue.

**Comment by GauravAndroidIS** [comment]
Hey divyank I have checked sdk is getting open but when I click on proceed
button which is the recommended one after that it ask me for captcha after
entering captcha it is throwing me error.

**Comment by divyank96** [comment]
Can you please share the error message here what error exactly it's showing?

**Comment by GauravAndroidIS** [comment]
Will share the error with you once I reached home. Also can you please also
let me know what is the flow of the sdk when I enter captcha?

**Comment by divyank96** [comment]
Okay! No problem and after entering Captcha you need to enter 4 digit share code and then you need to enter 6 digit otp received on your phone after that if you send "Y " for face match then it will open camera screen otherwise it will end the flow after entering otp only

**Comment by GauravAndroidIS** [comment]
Okay so what in case if user aadhar card is not linked with his/her number
or email I'd?

**Comment by divyank96** [comment]
then you will not get the OTP and you can't able to perform offline Aadhaar authentication number must required to link with your aadhaar card

**Comment by divyank96** [comment]
For any issues other than SDK integration please contact support@aadhaarapi.com.

**Comment by GauravAndroidIS** [comment]
I have checked the issue. This is the error we are getting

{who=null, request=2100, result=400, data=Intent { (has extras) }}

**Comment by GauravAndroidIS** [comment]
I have also checked when i am on my mobile network then i am getting data
but when i am on wifi sdk is not working and wifi is working properly.


I am getting this data when i am using mobile network:


{"id":"ebae3ef2-f2c6-4438-9320-e0e01cb08eb6","env":1,"mode":null,"transaction_status":6,"internal_status":"ZOOP_020","transaction_attempts":0,"public_ip":null,"request_medium":null,"response_url":"https:\/\/
preprod.aadhaarapi.com","response_to_agency":"N","face_match":"Y","facematch_score":null,"face_match_resp":null,"face_match_remark":null,"face_match_txn":null,"request_consent":"N","purpose":"User
Authentication","request_timestamp":"2020-02-06 21:49:58:220
+05:30","response_timestamp":"2020-02-06 21:49:58:223
+05:30","face_match_type":"S","sdk_response":"Aadhaar number does not have
mobile number.","transaction_data":null}

**Comment by divyank96** [comment]
Yes, your phone number is not linked with your aadhaar that's why it's showing you ("sdk_response":"Aadhaar number does not have mobile number") and the other issue you have asked it's strange that it is working on mobile data but not wifi so I checked it on my end it's working absolutely fine if there is proper network on wifi can you please try it again on different wifi network or tomorrow on same wifi network if there is proper connectivity let me know if you face the same issue again in proper connectivity.
